// Turns the recorded kane-cli streams beside this file into fixtures.ts, which tests import
// (a test reads no files). Run after adding or re-recording a stream: node tests/fixtures/build.mjs
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const names = readdirSync(here).filter(f => f.endsWith('.ndjson')).sort()
const camel = f => f.replace(/\.ndjson$/, '').replace(/-(\w)/g, (_, c) => c.toUpperCase())
const body = names.map(f => `/** ${f} */\nexport const ${camel(f)} = ${JSON.stringify(readFileSync(join(here, f), 'utf8'))}`).join('\n\n')
writeFileSync(join(here, 'fixtures.ts'), `// Generated by build.mjs from the recorded streams in this folder. Do not edit.\n\n${body}\n`)
console.log(`fixtures.ts: ${names.length} streams`)
